name: CI + CD demo pipeline

# Define when the workflow should run. On a push to main, a PR to main or manually with workflow_dispatch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Define some jobs that should run

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: echo Imagine we are compling our code here!

  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo Your code is being deployed to dev.myapp.com!

# Our deployment to Staging environment job
  DeployStaging:
    name: Deploy to DeployStaging
    if: github.event.ref == 'refs/heads/main'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo Your code is being deployed to staging at http://test.myapp.com
  
# Our deployment to production job

  DeployProduction:
    name: Deploy to production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    steps: 
      - name: Deploy
        run: echo The app is live at http://www.myapp.com
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
